language: python
cache: pip
os:
- linux
env:
  matrix:
  - TOX_ENV=python
  - TOX_ENV=flake8
  - TOX_ENV=spelling
  - TOX_ENV=package
install:
- sudo apt-get install python-enchant -y
- pip install --upgrade pip
- pip install tox coveralls
script:
- tox -e $TOX_ENV
after_success: test $TOX_ENV = "python" && coveralls
deploy:
- provider: pypi
  user: Myoldmopar
  skip_cleanup: true
  skip_upload_docs: true
  password:
    secure: Iy2tGAryeQ+ij8ZnKxXPRF+g2Wv/z/7AXsek4gcQbva8ymiURa+4JecjDifftqjW3/qUk+c1Ln22SH26NlYDAP1g8r4kyrZFzCKIIPQNNlej3Qri3+f6GWRMHCfjD6fKNPCxufg1ZoYF7EqPctW3FGGVD7zW2POkqSp2KKDyet6VkqLADiQMWx681HaPjPoWciID6/05+8B9QCqG4oEmkfUqaGV3KuYtZI7Oc6uQDs/Xjhuv6PRumNlo7BfzUQSe05nop3ALI6XyngaB60+pz3tAJVv2wTzUC8vA99Ajo1cwGtbNvUnI7COb5Os9QoMDzVCFBUBCpa6zNxuGyzPGHc0Du0Gv3afyNYLqfsunPzOUg1v597P8hE41TSGqD0FTUnb8cXnDxrprhucgTzxdpuVGHYk925bQVLvjFYQ186Gi3VZR/WrFZns2dOcyk2inaDe+HOiS/yh+5HGnLG5rDZutfTuDcI62DbKppScyucpanhD7WaYieLbZakB+WJB5tvaSQhmHg8D89MdnGXzYMyCiMirO14EnvvEm3jkPcMkUPxodiu+iHk2VvZoa+AKFYMlHrcgJuyqZNxKvvNy6unZzNxlooGny/sL8gWCcS3qqvRn1UzAIeEqgYtop180tIPoUKRDmpzFMrhqhLyuTC9E4HVuJ2AMtcOotxBEXcP0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Myoldmopar/py-idd-idf
    condition: $TOX_ENV = package
