language: python

python:
  - "2.7"

cache: pip

env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=spelling
    - TOX_ENV=package

install:
  - pip install --upgrade pip
  - pip install tox
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success: test $TOX_ENV = "python" && coveralls
